name: aerospike-redis-compare

services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "0.0.0.0:6381:6379"

  redis-app:
    build:
      context: ../
      dockerfile: container/redis-app/Dockerfile
    container_name: redis-app
    depends_on:
      - redis
    command: ["node", "dist/main.js"]
    volumes:
      - ../source/redis-app:/usr/src/app
    working_dir: /usr/src/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
        reservations:
          cpus: "0.25"
          memory: 152M

  aerospike:
    image: aerospike/aerospike-server:latest
    container_name: aerospike-container
    ports:
      - "0.0.0.0:3004:3000"
      - "0.0.0.0:3001:3001"
      - "0.0.0.0:3002:3002"
      - "0.0.0.0:3003:3003"

  aerospike-app:
    build:
      context: ../
      dockerfile: container/aerospike-app/Dockerfile
    container_name: aerospike-app
    depends_on:
      - aerospike
    environment:
      - AEROSPIKE_HOST=aerospike
      - AEROSPIKE_PORT=3004
    command: ["node", "dist/main.js"]
    volumes:
      - ../source/aerospike-app:/usr/src/app
    working_dir: /usr/src/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
        reservations:
          cpus: "0.25"
          memory: 152M
