name: aerospike-redis-benchmark

services:
  benchmark:
    build:
      context: ../
      dockerfile: container/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      aerospike:
        condition: service_healthy
    networks:
      - benchmark-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AEROSPIKE_HOST=aerospike
      - AEROSPIKE_PORT=3000
    restart: on-failure

  redis:
    image: redis:latest
    ports:
      - "6389:6379"
    networks:
      - benchmark-network
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  aerospike:
    image: aerospike/aerospike-server:latest
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    networks:
      - benchmark-network
    volumes:
      - aerospike-data:/opt/aerospike/data
      - ./aerospike/aerospike.conf:/etc/aerospike/aerospike.conf
    healthcheck:
      test: ["CMD", "/usr/bin/asinfo", "-p", "3000", "-v", "status"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  benchmark-network:
    driver: bridge

volumes:
  redis-data:
  aerospike-data: